---
kind: nomad
dry_run: true
excludes:
  weekdays:
    - Sun
    - Sat
  times_of_day:
    - 22:00-08:00
    - 11:00-14:00
  days_of_year:
    - Jan01
    - Apr01
    - May01
    - Aug01
    - Dec24
configs:
  namespace_denylist:
    - default
  signals:
    - SIGKILL
  job_type_skiplist:
    - system
    - batch
    - sysbatch
  job_skiplist:
    - prometheus
  # Add a meta tag on in your nomad job "chaotic" = False to opt-out
  job_meta_opt_key: chaotic
