name: Flake8

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: GitHub Action for Flake8
      uses: cclauss/GitHub-Action-for-Flake8@v0.5.0
